// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Backup struct {
	ID        string
	GuildID   string
	Data      string
	CreatedAt string
	UpdatedAt string
	CreatedBy string
}
