// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBackup = `-- name: CreateBackup :execresult
INSERT INTO backups (id, guild_id, data, created_by) VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = datetime('now')
`

type CreateBackupParams struct {
	ID        string
	GuildID   string
	Data      string
	CreatedBy string
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBackup,
		arg.ID,
		arg.GuildID,
		arg.Data,
		arg.CreatedBy,
	)
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBackup, id)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, guild_id, data, created_at, updated_at, created_by FROM backups WHERE id = ?
`

func (q *Queries) GetBackup(ctx context.Context, id string) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listBackups = `-- name: ListBackups :many
SELECT id, guild_id, data, created_at, updated_at, created_by FROM backups WHERE created_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListBackups(ctx context.Context, createdBy string) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
